name: Maven Build Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Build Maven Project
      run: |
        mvn clean install

    - name: Display Maven Goals Output
      run: |
        mvn validate
        mvn compile
        mvn test
        mvn package
        mvn verify
        mvn install
        mvn site
        mvn deploy
        mvn clean

